version: '3.8'
services:
  db:
    image: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'test'

  app:
    build: .
    volumes:
      - ./:/usr/src/application:ro
    command: flask --app main run --reload
    environment:
      MYSQL_HOST: 'db'
      MYSQL_PORT: '3306'
      MYSQL_USERNAME: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'test'
    ports:
      - 8000:8000